#!/usr/bin/env bash

# Block script on MacOS
if [ $( uname -s ) == "Darwin" ]; then
    echo "You're on MacOS, not touching SSH keys"
    exit 0
fi

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
DOTFILE_DIR="$( realpath "${SCRIPT_DIR}/../../" )"

for file in $DOTFILE_DIR/ssh/*
do
    if [ "$file" != "${file%.pub}" ]; then
        continue;
    fi

    if [ -f "${file}.asc" ]; then
        continue;
    fi

    echo "[GPG] Encrypting $( basename "$file" ) ⇒ $( basename "${file}.asc" )"
    gpg --encrypt --interactive --armor --recipient github@roelof.io "$file"
done
