#!/usr/bin/env bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
DOTFILE_DIR="$( realpath "${SCRIPT_DIR}/../../" )"

for file in $DOTFILE_DIR/ssh/*
do
    if [ "$file" = "${file%.asc}" ]; then
        continue;
    fi

    if [ -f "${file%.asc}" ]; then
        continue;
    fi

    echo "[GPG] Decrypting $( basename "$file" ) ⇒ $( basename "${file%.asc}" )"
    gpg --decrypt --armor "$file"
done
