#!/usr/bin/env bash

DOTFILE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && git rev-parse --show-toplevel )"

test -f "$DOTFILE_DIR/config/git/ignore" && exit 0

echo "Downloading gitignore file"
curl \
    --location \
    --output - \
    --output - \
    https://gist.githubusercontent.com/octocat/9257657/raw/.gitignore \
    https://gitignore.io/api/linux,macos,sublimetext,phpstorm,vscode \
    > "$DOTFILE_DIR/config/git/ignore"
