#!/usr/bin/env bash

DOTFILE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && git rev-parse --show-toplevel )"

test -f "$DOTFILE_DIR/config/git/ignore" && exit 0

DEVICE_TYPE=linux
if [ $( uname -s ) == "Darwin" ]; then
    DEVICE_TYPE=macos
fi

echo "Downloading gitignore file"
curl \
    --location \
    --output - \
    --output - \
    "https://gitignore.io/api/${DEVICE_TYPE},sublimetext,phpstorm,vscode" \
    > "$DOTFILE_DIR/config/git/ignore"
