#!/usr/bin/env bash

set -e


function make_screenshot() {
    shot_dir="$( xdg-user-dir PICTURES )"
    shot_date="$(date +%Y%m%d-%H-%M-%S)"
    shot_file="$shot_dir/screenshot_$shot_date.png"
    gnome-screenshot --file="$shot_file" $@
    if [ -f "$shot_file" ]; then
        notify-send \
            "Screenshot taken" \
            "Saved as $( basename "$shot_file" ) and on clipboard"
        xclip \
            -selection clipboard \
            -t image/png \
            "$shot_file"
    elif [ "$1" != "--area" ]; then
        notify-send \
            "Screenshot failed" \
            "Failed to take screenshot"
    fi
}

case "$1" in
    area)
        make_screenshot \
            --area
        ;;
    window)
        make_screenshot \
            --window \
            --border-effect=shadow
        ;;
    full)
        make_screenshot
        ;;
    *)
        gnome-screenshot \
            --interactive
        ;;
esac
