#!/usr/bin/env bash

set -xe

shot_file="${HOME}/pictures/screenshot_$(date +%Y%m%d-%H-%M-%S).jpg"

case "$1" in
    area)
        gnome-screenshot \
            --area \
            --clipboard \
            --file="$shot_file"
        ;;
    window)
        gnome-screenshot \
            --window \
            --border-effect=shadow \
            --clipboard \
            --file="$shot_file"
        ;;
    full)
        gnome-screenshot \
            --clipboard \
            --file="$shot_file"
        ;;
    *)
        gnome-screenshot \
            --interactive \
            --clipboard \
            --file="$shot_file"
        ;;
esac
