#!/usr/bin/env bash

set -xe

DIR="${HOME}/pictures"
FILENAME="shot_$(date +%Y%m%d-%H-%M-%S)"

if [ "$1" = "m" ]; then
	maim \
		--color='0.1,0.4,1.0,0.6' --highlight \
		--hidecursor \
		--select \
		-- "${DIR}/${FILENAME}-selection.png"
else
	maim \
		--hidecursor \
		-- "${DIR}/${FILENAME}-full.png"
fi
