#!/usr/bin/env bash

BINARY="$HOME/bin/random-wallpaper"

if crontab -l 2>/dev/null | grep --quiet "$BINARY"; then
    exit 0
fi

if ! type convert > /dev/null 2>&1; then
    exit 0
fi

MINUTE=$(( $RANDOM % 30 + 1 ))
SECOND_MINUTE=$(( $MINUTE + 30 ))

crontab - <<DOC
$( crontab -l)

# Auto refresh wallaper every 30 minutes
$MINUTE,$SECOND_MINUTE * * * * $BINARY > /dev/null 2>&1
DOC

echo "[Wallpaper Cron] Job set for $MINUTE and $SECOND_MINUTE minutes past the hour"
