#!/usr/bin/env bash

test -f "$HOME/bin/plantuml.jar" && exit 0

echo "Downloading PlantUML"

curl \
    --location \
    --output "$HOME/bin/plantuml.jar" \
    https://github.com/plantuml/plantuml/releases/download/v1.2022.5/plantuml-1.2022.5.jar
