#!/usr/bin/env bash

# Block script on MacOS
if [ $( uname -s ) == "Darwin" ]; then
    echo "You're on MacOS, not installing PlantUML"
    exit 0
fi

test -f "$HOME/bin/plantuml.jar" && exit 0

echo "Downloading PlantUML"

curl \
    --location \
    --output "$HOME/bin/plantuml.jar" \
    https://github.com/plantuml/plantuml/releases/download/v1.2022.5/plantuml-1.2022.5.jar
